In [1]:
import cv2
from PIL import Image
import skimage.measure
import numpy as np


In [2]:
# To read image from disk, we use
# cv2.imread function, in below method,
img = cv2.imread("Production Data/1444-312-A/1444-312-A_Img/0.jpg", cv2.IMREAD_COLOR)
# for  find image height,width,and channels(rgb or grayscale)
print(img)
img_shape=img.shape
print("img_shape:", img_shape)

[[[15 15 15]
  [ 1  1  1]
  [ 1  1  1]
  ...
  [15 15 15]
  [15 15 15]
  [15 15 15]]

 [[14 14 14]
  [ 0  0  0]
  [ 1  1  1]
  ...
  [13 13 13]
  [13 13 13]
  [14 14 14]]

 [[13 13 13]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [12 12 12]
  [12 12 12]
  [13 13 13]]

 ...

 [[32 32 32]
  [ 8  8  8]
  [ 8  8  8]
  ...
  [32 32 32]
  [33 33 33]
  [33 33 33]]

 [[29 29 29]
  [ 5  5  5]
  [ 6  6  6]
  ...
  [30 30 30]
  [30 30 30]
  [30 30 30]]

 [[26 26 26]
  [ 2  2  2]
  [ 3  3  3]
  ...
  [26 26 26]
  [26 26 26]
  [25 25 25]]]
img_shape: (1280, 1024, 3)


In [3]:
img_height=img_shape[0]
img_width=img_shape[1]

print(img_height)
print(img_width)

1280
1024


In [4]:
pilimg=Image.fromarray(img)
pilimg.show()

In [5]:
# for pooling
poolimg=skimage.measure.block_reduce(img, (3,3), np.max)
poolimg

ValueError: `block_size` must be a scalar or have the same length as `image.shape`

In [ ]:
pilimg=Image.fromarray(img)
pilimg.show()