In [1]:
import cv2
import numpy as np
from PIL import Image
from skimage.feature import corner_harris, corner_subpix, corner_peaks


In [2]:
img = cv2.imread("147.jpg")

In [3]:
print(img.shape)
# The image with shape (1280, 1024, 3) has a resolution of 1280 pixels by 1024 pixels and has 3 color channels, which means it is a color image.

(1280, 1024, 3)


In [4]:
print(img.size)

3932160


In [5]:
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [6]:
blur_img = cv2.GaussianBlur(gray_img, (5, 5), 0)

In [7]:
# Compute Harris corners
corners = corner_harris(blur_img, k=0.04)
corners

array([[ 5.25046409e-07,  6.37126749e-07,  1.87674659e-07, ...,
         8.41628209e-06,  6.84258877e-05,  6.68851401e-05],
       [ 4.60584155e-07,  5.49769319e-07,  1.71791356e-07, ...,
         1.60742806e-05,  7.40552337e-05,  7.29489797e-05],
       [ 6.05980174e-08,  2.16746674e-08, -3.72703946e-08, ...,
         5.59365150e-06,  1.93729362e-05,  1.44620127e-05],
       ...,
       [ 3.86350126e-06,  5.77160266e-06,  2.20002774e-06, ...,
         9.40897948e-05,  2.86784645e-04,  1.33325008e-04],
       [ 2.29084823e-05,  2.75182483e-05,  9.74893105e-06, ...,
         1.89039629e-04,  7.85309431e-04,  6.54708938e-04],
       [ 2.13651664e-05,  2.52299363e-05,  7.65693018e-06, ...,
         7.07204792e-05,  6.11960224e-04,  5.41022314e-04]])

In [13]:
# Subpixel corner refinement
corners = corner_subpix(blur_img, corners, window_size=13)

ValueError: Integer argument required but received [[6.00000053 6.00000064 6.00000019 ... 6.00000842 6.00006843 6.00006689]
 [6.00000046 6.00000055 6.00000017 ... 6.00001607 6.00007406 6.00007295]
 [6.00000006 6.00000002 5.99999996 ... 6.00000559 6.00001937 6.00001446]
 ...
 [6.00000386 6.00000577 6.0000022  ... 6.00009409 6.00028678 6.00013333]
 [6.00002291 6.00002752 6.00000975 ... 6.00018904 6.00078531 6.00065471]
 [6.00002137 6.00002523 6.00000766 ... 6.00007072 6.00061196 6.00054102]], check inputs.

In [9]:
# Find the peaks of the corners
coords = corner_peaks(corners, min_distance=5)
coords

array([[379, 361],
       [730, 668],
       [725, 643],
       ...,
       [108,  22],
       [  5,  50],
       [ 53,  43]], dtype=int64)

In [10]:
# Find contours
contours, hierarchy = cv2.findContours(blur_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
print(contours, hierarchy)

(array([[[   0,    0]],

       [[   0, 1279]],

       [[1023, 1279]],

       [[1023,    0]],

       [[ 547,    0]],

       [[ 546,    1]],

       [[ 545,    1]],

       [[ 544,    0]],

       [[ 523,    0]],

       [[ 523,    5]],

       [[ 521,    7]],

       [[ 520,    6]],

       [[ 520,    0]],

       [[   9,    0]],

       [[   9,    7]],

       [[   8,    8]],

       [[   3,    8]],

       [[   2,    7]],

       [[   2,    0]]], dtype=int32), array([[[ 134, 1169]],

       [[ 135, 1168]],

       [[ 136, 1169]],

       [[ 135, 1170]]], dtype=int32), array([[[  5, 275]],

       [[  6, 274]],

       [[  7, 274]],

       [[  8, 275]],

       [[  8, 276]],

       [[  7, 277]]], dtype=int32), array([[[ 29, 253]],

       [[ 30, 252]],

       [[ 31, 252]],

       [[ 32, 253]],

       [[ 32, 254]],

       [[ 30, 256]],

       [[ 29, 255]]], dtype=int32), array([[[ 25, 248]],

       [[ 26, 247]],

       [[ 28, 249]],

       [[ 28, 250]],

       [[ 27, 251

In [11]:
# Draw contours
cv2.drawContours(img, contours, -1, (0, 255, 0), 2)

array([[[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [ 12,  12,  12],
        [  0, 255,   0],
        [  0, 255,   0]],

       ...,

       [[  0, 255,   0],
        [  0, 255,   0],
        [  4,   4,   4],
        ...,
        [ 30,  30,  30],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]],

       [[  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0],
        ...,
        [  0, 255,   0],
        [  0, 255,   0],
        [  0, 255,   0]]

In [12]:
# SIFT Feature Detection
sift = cv2.xfeatures2d.SIFT_create()
kp, des = sift.detectAndCompute(gray_img, None)

AttributeError: module 'cv2' has no attribute 'xfeatures2d'

In [ ]:
# Draw keypoints on the image
img_with_keypoints = cv2.drawKeypoints(img, kp, None)